#---------------------------------------------
# notices.http
# 공지사항 게시글 API > 일부 admin 권한 필요가능
#---------------------------------------------

#====================================== 페이지네이션 기능 (공통 모듈) ==============================================================================================
# Default Page Number = 1
# Default Page Size = 10

### 1. 페이징 조회 (페이지 정보까지 조회)
GET http://localhost:8080/v1/notices/pagination
    ?page=1
    &size=3
    &sort=noticeIndex

### 2. 페이징 및 정렬 조회 (페이지 정보까지 조회)
GET http://localhost:8080/v1/notices/pagination
    ?page=1
    &size=3
    &sort=noticeIndex,desc

### 3. 정렬 조회 (페이지 정보까지 조회)
GET http://localhost:8080/v1/notices/pagination
    ?sort=noticeIndex,desc

### 4. 다른 Column을 기준으로 페이징 및 정렬 조회 (페이지 정보까지 조회)
GET http://localhost:8080/v1/notices/pagination
    ?sort=noticeContents

### 5. 페이징 조회 (데이터만 조회)
GET http://localhost:8080/v1/notices/pagination/contents
    ?page=1
    &size=5
    &sort=noticeIndex

### 6. 페이징 및 정렬 조회 (데이터만 조회)
GET http://localhost:8080/v1/notices/pagination/contents
    ?page=1
    &size=5
    &sort=noticeIndex,desc

### 7. 정렬 조회 (데이터만 조회)
GET http://localhost:8080/v1/notices/pagination/contents
    ?sort=noticeIndex,desc

#================================================================================================================================================================

#---------------------------------------------

#======================================= 추가 구현된 기능 =======================================================================================================

### 8. 공지사항 게시글 번호를 조건으로 단건 조회
GET http://localhost:8080/v1/notices/:10


### 9. 공지사항 게시글 제목을 조건으로 단건 조회
GET http://localhost:8080/v1/notices/
    ?subject=TEST10


### 10. 새로운 공지사항 게시글 등록
POST http://localhost:8080/v1/notices
Content-Type: application/json

{
    "subject": "TEST15",
    "contents": "CONTENT0015",
    "ipAddr": "127.0.0.1",
    "writeId": "user1",
    "isActive": "Y",
    "hitCnt": 0                         
}

### 11. 기존 공지사항 게시글 수정
PUT http://localhost:8080/v1/notices/:15
Content-Type: application/json

{
    "subject": "EDITED_TEST15",
    "contents": "EDITED_CONTENT0015",
    "hitCnt": 0,
    "ipAddr": "127.0.0.1",
    "isActive": "Y",
    "modifyId": "user1"
}

### 12. 기존 공지사항 게시글 삭제
DELETE http://localhost:8080/v1/notices/:15

#================================================================================================================================================================